# Generated by Django 4.2.7 on 2023-12-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_isbn_book_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back']},
        ),
        migrations.RenameField(
            model_name='bookinstance',
            old_name='due_book',
            new_name='due_back',
        ),
    ]
